### ISSUE TITLE
Small bug fixes

### ISSUE THREAD

**Issue by ifdefelse** [MariusVanDerWijden/progpowWiki#1]
Thanks for porting the spec to a python-style spec to match ethash.  I noticed 3 small bugs:
1) sizeof(uint32_t) = 4 (bytes), not 32
2) there's a sizeof(uint32_t) call that should be replaced with 4
3) the final data_g merge loop should start at index 1 - data_g[0] was already merged into mix[0].

**Comment by MariusVanDerWijden** [comment]
Thank you very much, I fixed it!

**Comment by ifdefelse** [comment]
Shouldn't the data_g loop be range(1, PROGPOW_DAG_LOADS-1)?

**Comment by MariusVanDerWijden** [comment]
No, in python the range command only specifies the bounds. The following code is equivalent:

```
for i in range(1, 5):
    print "Hello World!\n"
```
```
for(int i = 1; i < 5; i++)
        printf("Hello World\n");
```
both produce four lines of output
